import React, {useEffect, useRef, useState} from 'react';
import {ActivityIndicator, Animated, Easing, FlatList, Image, ImageBackground, ListRenderItemInfo, NativeScrollEvent, NativeSyntheticEvent, Pressable, StatusBar, StyleSheet, Text, useWindowDimensions, View} from 'react-native';
import {SafeAreaProvider, useSafeAreaInsets} from 'react-native-safe-area-context';
import {WebView} from 'react-native-webview';

const images = {
  logo: require('./src/assets/images/cedugames-logo.png'),
  splash: require('./src/assets/images/splash-background.png'),
  learn: require('./src/assets/images/learn-through-play.png'),
  adventure: require('./src/assets/images/age-adventure.png'),
  coin: require('./src/assets/images/reward-coin.png'),
  trophy: require('./src/assets/images/reward-trophy.png'),
  math: require('./src/assets/images/math.png'),
  english: require('./src/assets/images/english.png'),
  badge: require('./src/assets/images/badge.png'),
};
const colors = {red: '#F02229', orange: '#FA7E14', yellow: '#FECB03', blue: '#0177D2', purple: '#6336AA', pink: '#EF387E', ink: '#24123F', cream: '#FFF9EF'};
type Slide = {id: string; eyebrow: string; title: string; description: string; color: string; pale: string; kind: 'learn' | 'adventure' | 'rewards'};
const slides: Slide[] = [
  {id: 'learn', eyebrow: 'LEARN THROUGH PLAY', title: 'Big ideas become fun games', description: 'Build confidence in Maths and English with quick challenges made to feel like playtime.', color: colors.blue, pale: '#EAF7FF', kind: 'learn'},
  {id: 'adventure', eyebrow: 'MADE JUST FOR YOU', title: 'Choose your own adventure', description: 'Pick your age crew, explore colourful subjects, and move through levels at your perfect pace.', color: colors.purple, pale: '#F5ECFF', kind: 'adventure'},
  {id: 'rewards', eyebrow: 'PLAY • GROW • SHINE', title: 'Every win feels rewarding', description: 'Earn fun coins, unlock rewards, grow your streak, and celebrate your place on the leaderboard.', color: colors.orange, pale: '#FFF4DE', kind: 'rewards'},
];

function App() {
  const [showSplash, setShowSplash] = useState(true);
  const [done, setDone] = useState(false);
  const [showLogin, setShowLogin] = useState(false);
  return <SafeAreaProvider><StatusBar barStyle={showSplash ? 'light-content' : 'dark-content'} />{showSplash ? <AnimatedSplash onComplete={() => setShowSplash(false)} /> : showLogin ? <LoginWebView /> : done ? <Welcome onStart={() => setShowLogin(true)} /> : <Onboarding onComplete={() => setDone(true)} />}</SafeAreaProvider>;
}

function AnimatedSplash({onComplete}: {onComplete: () => void}) {
  const scale = useRef(new Animated.Value(0.72)).current;
  const opacity = useRef(new Animated.Value(0)).current;
  const lift = useRef(new Animated.Value(18)).current;
  const breathe = useRef(new Animated.Value(1)).current;
  const dots = useRef([new Animated.Value(0), new Animated.Value(0), new Animated.Value(0)]).current;
  useEffect(() => {
    const dotAnimations = dots.map((value, index) => Animated.loop(Animated.sequence([
      Animated.delay(index * 120),
      Animated.timing(value, {toValue: -9, duration: 260, easing: Easing.out(Easing.quad), useNativeDriver: true}),
      Animated.timing(value, {toValue: 0, duration: 260, easing: Easing.in(Easing.quad), useNativeDriver: true}),
      Animated.delay(360 - index * 120),
    ])));
    dotAnimations.forEach(animation => animation.start());
    const logoEntrance = Animated.parallel([
      Animated.spring(scale, {toValue: 1, friction: 5, tension: 52, useNativeDriver: true}),
      Animated.timing(opacity, {toValue: 1, duration: 520, useNativeDriver: true}),
      Animated.timing(lift, {toValue: 0, duration: 620, easing: Easing.out(Easing.cubic), useNativeDriver: true}),
    ]);
    const logoBreathing = Animated.loop(Animated.sequence([
      Animated.timing(breathe, {toValue: 1.045, duration: 620, easing: Easing.inOut(Easing.sin), useNativeDriver: true}),
      Animated.timing(breathe, {toValue: 1, duration: 620, easing: Easing.inOut(Easing.sin), useNativeDriver: true}),
    ]));
    logoEntrance.start(({finished}) => finished && logoBreathing.start());
    const timer = setTimeout(onComplete, 2200);
    return () => {clearTimeout(timer); logoEntrance.stop(); logoBreathing.stop(); dotAnimations.forEach(animation => animation.stop());};
  }, [breathe, dots, lift, onComplete, opacity, scale]);
  return <ImageBackground source={images.splash} style={styles.splash} resizeMode="cover"><View style={styles.splashShade} /><Animated.View style={[styles.splashLogoFrame, {opacity, transform: [{translateY: lift}, {scale}, {scale: breathe}]}]}><Image source={images.logo} resizeMode="contain" style={styles.splashLogo} /></Animated.View><Text style={styles.splashMessage}>Loading your adventure...</Text><View style={styles.loadingDots}>{dots.map((value, index) => <Animated.View key={index} style={[styles.loadingDot, {backgroundColor: [colors.red, colors.yellow, colors.blue][index], transform: [{translateY: value}]}]} />)}</View></ImageBackground>;
}

function Onboarding({onComplete}: {onComplete: () => void}) {
  const {width} = useWindowDimensions();
  const insets = useSafeAreaInsets();
  const listRef = useRef<FlatList<Slide>>(null);
  const [index, setIndex] = useState(0);
  const next = () => {if (index === slides.length - 1) return onComplete(); listRef.current?.scrollToIndex({index: index + 1, animated: true}); setIndex(index + 1);};
  const onMomentumEnd = (event: NativeSyntheticEvent<NativeScrollEvent>) => setIndex(Math.round(event.nativeEvent.contentOffset.x / width));
  const renderSlide = ({item}: ListRenderItemInfo<Slide>) => <View style={[styles.slide, {width, backgroundColor: item.pale}]}><View style={[styles.bubble, styles.bubbleTop, {backgroundColor: item.color}]} /><View style={[styles.bubble, styles.bubbleBottom, {backgroundColor: item.color}]} /><View style={[styles.artStage, {backgroundColor: item.color}]}><View style={styles.stageGlow} /><View style={styles.stageDots}><Text style={styles.stageDotsText}>.  .  .</Text></View><SlideArtwork kind={item.kind} /></View><View style={styles.slideCopy}><View style={[styles.eyebrowPill, {backgroundColor: `${item.color}14`}]}><Text style={[styles.eyebrow, {color: item.color}]}>{item.eyebrow}</Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.description}>{item.description}</Text></View></View>;
  return <View style={styles.onboarding}><View style={[styles.topBar, {paddingTop: insets.top + 10}]}><Image source={images.logo} resizeMode="contain" style={styles.topLogo} /><View style={styles.topActions}><View style={[styles.stepPill, {borderColor: `${slides[index].color}33`}]}><Text style={[styles.stepText, {color: slides[index].color}]}>0{index + 1}</Text><Text style={styles.stepTotal}> / 03</Text></View><Pressable accessibilityRole="button" onPress={onComplete} hitSlop={12} style={({pressed}) => [styles.skipButton, pressed && styles.pressed]}><Text style={styles.skipText}>Skip</Text></Pressable></View></View><FlatList ref={listRef} data={slides} keyExtractor={item => item.id} renderItem={renderSlide} horizontal pagingEnabled bounces={false} showsHorizontalScrollIndicator={false} onMomentumScrollEnd={onMomentumEnd} /><View style={[styles.bottomBar, {paddingBottom: Math.max(insets.bottom, 18)}]}><View><Text style={styles.progressLabel}>YOUR ADVENTURE</Text><View style={styles.pagination}>{slides.map((slide, dotIndex) => <View key={slide.id} style={[styles.pageDot, dotIndex === index && [styles.pageDotActive, {backgroundColor: slides[index].color}]]} />)}</View></View><Pressable accessibilityRole="button" onPress={next} style={({pressed}) => [styles.nextButton, {backgroundColor: slides[index].color}, pressed && styles.pressed]}><Text style={styles.nextText}>{index === slides.length - 1 ? "Let's play!" : 'Explore'}</Text><View style={styles.arrowCircle}><Text style={[styles.nextArrow, {color: slides[index].color}]}>›</Text></View></Pressable></View></View>;
}

function SlideArtwork({kind}: {kind: Slide['kind']}) {
  if (kind === 'rewards') return <RewardArtwork />;
  if (kind === 'learn') return <View style={styles.learnScene}><View style={[styles.orbit, styles.orbitOne]} /><View style={[styles.orbit, styles.orbitTwo]} /><View style={[styles.subjectCard, styles.mathCard]}><Image source={images.math} style={styles.subjectIcon} resizeMode="contain" /><Text style={[styles.subjectLabel, {color: colors.blue}]}>MATHS</Text></View><View style={[styles.subjectCard, styles.englishCard]}><Image source={images.english} style={styles.subjectIcon} resizeMode="contain" /><Text style={[styles.subjectLabel, {color: colors.pink}]}>ENGLISH</Text></View><View style={styles.heroDisc}><Image source={images.learn} resizeMode="contain" style={styles.learnArt} /></View><View style={styles.xpChip}><Text style={styles.xpText}>+25 XP</Text></View></View>;
  return <View style={styles.adventureScene}><View style={styles.rainbowOne} /><View style={styles.rainbowTwo} /><View style={styles.rainbowThree} /><View style={styles.adventurePortrait}><Image source={images.adventure} resizeMode="cover" style={styles.adventureArt} /></View><View style={[styles.ageChip, styles.ageChipOne]}><Text style={styles.ageChipText}>4-6</Text><Text style={styles.ageChipSub}>EXPLORER</Text></View><View style={[styles.ageChip, styles.ageChipTwo]}><Text style={styles.ageChipText}>7-9</Text><Text style={styles.ageChipSub}>ADVENTURER</Text></View><View style={[styles.ageChip, styles.ageChipThree]}><Text style={styles.ageChipText}>10+</Text><Text style={styles.ageChipSub}>CHALLENGER</Text></View></View>;
}

function RewardArtwork() {
  const float = useRef(new Animated.Value(0)).current;
  useEffect(() => {const animation = Animated.loop(Animated.sequence([Animated.timing(float, {toValue: -10, duration: 950, useNativeDriver: true}), Animated.timing(float, {toValue: 0, duration: 950, useNativeDriver: true})])); animation.start(); return () => animation.stop();}, [float]);
  return <View style={styles.rewardArt}><View style={styles.rewardHalo} /><Text style={[styles.spark, styles.sparkOne]}>+</Text><Text style={[styles.spark, styles.sparkTwo]}>*</Text><View style={styles.badgeCard}><Image source={images.badge} style={styles.badgeImage} resizeMode="contain" /><View><Text style={styles.badgeTitle}>LEVEL UP!</Text><Text style={styles.badgeSub}>Super learner</Text></View></View><Animated.Image source={images.trophy} resizeMode="contain" style={[styles.trophy, {transform: [{translateY: float}]}]} /><Image source={images.coin} resizeMode="contain" style={styles.coinLarge} /><Image source={images.coin} resizeMode="contain" style={styles.coinSmall} /><View style={styles.streakPill}><Text style={styles.streakText}>7 DAY STREAK</Text><View style={styles.streakFlame}><Text style={styles.streakFlameText}>7</Text></View></View></View>;
}

function Welcome({onStart}: {onStart: () => void}) {
  const insets = useSafeAreaInsets();
  return <View style={[styles.welcome, {paddingTop: insets.top, paddingBottom: insets.bottom}]}><View style={styles.welcomeCircle}><Image source={images.logo} resizeMode="contain" style={styles.welcomeLogo} /></View><Text style={styles.welcomeTitle}>Ready for an adventure?</Text><Text style={styles.welcomeDescription}>Your learning journey starts here.</Text><Pressable accessibilityRole="button" onPress={onStart} style={({pressed}) => [styles.startButton, pressed && styles.pressed]}><Text style={styles.startText}>Get started</Text></Pressable></View>;
}

function LoginWebView() {
  const insets = useSafeAreaInsets();
  return <View style={[styles.webScreen, {paddingTop: insets.top}]}><WebView source={{uri: 'https://cedugames-user.onrender.com/login'}} style={styles.webView} javaScriptEnabled domStorageEnabled sharedCookiesEnabled thirdPartyCookiesEnabled startInLoadingState renderLoading={() => <View style={styles.webState}><Image source={images.logo} resizeMode="contain" style={styles.webLogo} /><ActivityIndicator size="large" color={colors.purple} /><Text style={styles.webStateText}>Opening your adventure...</Text></View>} renderError={() => <View style={styles.webState}><Image source={images.logo} resizeMode="contain" style={styles.webLogo} /><Text style={styles.webErrorTitle}>We couldn't open the login page</Text><Text style={styles.webStateText}>Check your internet connection and try again.</Text></View>} /></View>;
}

const styles = StyleSheet.create({
  splash: {flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20}, splashShade: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(38,13,77,.18)'}, splashLogoFrame: {width: '100%', maxWidth: 520, height: 190, alignItems: 'center', justifyContent: 'center'}, splashLogo: {width: '100%', height: '100%'}, splashMessage: {fontFamily: 'Baloo2-SemiBold', color: '#FFF', fontSize: 17, marginTop: 28}, loadingDots: {height: 30, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18}, loadingDot: {width: 11, height: 11, borderRadius: 6},
  onboarding: {flex: 1, backgroundColor: colors.cream}, topBar: {position: 'absolute', zIndex: 5, left: 20, right: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, topLogo: {width: 124, height: 50}, topActions: {flexDirection: 'row', alignItems: 'center', gap: 10}, stepPill: {height: 34, borderWidth: 1, borderRadius: 17, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,.75)'}, stepText: {fontFamily: 'Baloo2-Bold', fontSize: 14}, stepTotal: {fontFamily: 'Baloo2-SemiBold', color: '#94899F', fontSize: 12}, skipButton: {height: 38, borderRadius: 19, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', elevation: 2}, skipText: {fontFamily: 'Baloo2-SemiBold', color: '#62576E', fontSize: 14},
  slide: {flex: 1, paddingTop: 98, paddingHorizontal: 18, overflow: 'hidden'}, bubble: {position: 'absolute', borderRadius: 999, opacity: .09}, bubbleTop: {width: 250, height: 250, right: -135, top: 35}, bubbleBottom: {width: 190, height: 190, left: -110, bottom: 105}, artStage: {height: '55%', minHeight: 320, maxHeight: 500, borderRadius: 42, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 5, borderColor: 'rgba(255,255,255,.7)', shadowColor: '#311150', shadowOffset: {width: 0, height: 18}, shadowOpacity: .2, shadowRadius: 24, elevation: 9}, stageGlow: {position: 'absolute', width: 310, height: 310, borderRadius: 155, backgroundColor: 'rgba(255,255,255,.18)', top: -105, right: -90}, stageDots: {position: 'absolute', top: 14, left: 22}, stageDotsText: {fontFamily: 'Baloo2-ExtraBold', color: 'rgba(255,255,255,.65)', fontSize: 28, letterSpacing: 5}, slideCopy: {alignItems: 'center', paddingTop: 22, paddingHorizontal: 8}, eyebrowPill: {paddingHorizontal: 14, paddingVertical: 6, borderRadius: 16}, eyebrow: {fontFamily: 'Baloo2-Bold', fontSize: 11, letterSpacing: 1.6}, title: {fontFamily: 'Baloo2-ExtraBold', fontSize: 30, lineHeight: 34, color: colors.ink, textAlign: 'center', marginTop: 9}, description: {fontFamily: 'Baloo2-Medium', fontSize: 15.5, lineHeight: 21, color: '#6F637D', textAlign: 'center', marginTop: 7, maxWidth: 390},
  learnScene: {width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center'}, orbit: {position: 'absolute', borderWidth: 1, borderColor: 'rgba(255,255,255,.3)', borderRadius: 999}, orbitOne: {width: 330, height: 330}, orbitTwo: {width: 245, height: 245}, heroDisc: {width: 242, height: 242, borderRadius: 121, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', elevation: 8, shadowColor: '#003E70', shadowOpacity: .25, shadowRadius: 18}, learnArt: {width: '92%', height: '92%'}, subjectCard: {position: 'absolute', zIndex: 4, width: 88, height: 106, borderRadius: 20, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', elevation: 7, shadowColor: '#152030', shadowOpacity: .22, shadowRadius: 12}, mathCard: {left: 12, top: 38, transform: [{rotate: '-8deg'}]}, englishCard: {right: 10, bottom: 35, transform: [{rotate: '8deg'}]}, subjectIcon: {width: 55, height: 55}, subjectLabel: {fontFamily: 'Baloo2-Bold', fontSize: 10, marginTop: 2}, xpChip: {position: 'absolute', right: 20, top: 28, borderRadius: 15, backgroundColor: colors.yellow, paddingHorizontal: 12, paddingVertical: 6, transform: [{rotate: '5deg'}], elevation: 4}, xpText: {fontFamily: 'Baloo2-ExtraBold', color: '#503A00', fontSize: 13},
  adventureScene: {width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center'}, rainbowOne: {position: 'absolute', width: 350, height: 350, borderRadius: 175, borderWidth: 42, borderColor: 'rgba(255,255,255,.14)', bottom: -150}, rainbowTwo: {position: 'absolute', width: 270, height: 270, borderRadius: 135, borderWidth: 28, borderColor: 'rgba(254,203,3,.45)', bottom: -110}, rainbowThree: {position: 'absolute', width: 210, height: 210, borderRadius: 105, backgroundColor: 'rgba(239,56,126,.35)', bottom: -85}, adventurePortrait: {width: 245, height: 245, borderRadius: 123, overflow: 'hidden', borderWidth: 7, borderColor: '#FFF', backgroundColor: '#EBD7FF', elevation: 8}, adventureArt: {width: '100%', height: '100%'}, ageChip: {position: 'absolute', minWidth: 82, borderRadius: 16, backgroundColor: '#FFF', paddingHorizontal: 10, paddingVertical: 7, alignItems: 'center', elevation: 6}, ageChipOne: {left: 10, bottom: 38, transform: [{rotate: '-7deg'}]}, ageChipTwo: {right: 8, top: 34, transform: [{rotate: '7deg'}]}, ageChipThree: {right: 14, bottom: 28, transform: [{rotate: '5deg'}]}, ageChipText: {fontFamily: 'Baloo2-ExtraBold', color: colors.purple, fontSize: 17, lineHeight: 18}, ageChipSub: {fontFamily: 'Baloo2-Bold', color: '#8A7D96', fontSize: 7, letterSpacing: .6},
  bottomBar: {backgroundColor: '#FFF', paddingHorizontal: 22, paddingTop: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', shadowColor: '#311150', shadowOffset: {width: 0, height: -10}, shadowOpacity: .08, shadowRadius: 20, elevation: 12}, progressLabel: {fontFamily: 'Baloo2-Bold', color: '#AAA0B2', fontSize: 8, letterSpacing: 1.3, marginBottom: 7}, pagination: {flexDirection: 'row', alignItems: 'center', gap: 7}, pageDot: {width: 9, height: 9, borderRadius: 5, backgroundColor: '#DDD6E5'}, pageDotActive: {width: 34}, nextButton: {height: 58, minWidth: 158, borderRadius: 22, paddingLeft: 22, paddingRight: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 13, shadowColor: '#352043', shadowOffset: {width: 0, height: 9}, shadowOpacity: .25, shadowRadius: 13, elevation: 6}, nextText: {fontFamily: 'Baloo2-Bold', fontSize: 17, color: '#FFF'}, arrowCircle: {width: 44, height: 44, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF'}, nextArrow: {fontFamily: 'Baloo2-Regular', fontSize: 34, lineHeight: 38, marginTop: -4}, pressed: {opacity: .84, transform: [{scale: .98}]},
  rewardArt: {width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center'}, rewardHalo: {position: 'absolute', width: 265, height: 265, borderRadius: 133, backgroundColor: 'rgba(255,255,255,.18)', borderWidth: 22, borderColor: 'rgba(255,255,255,.12)'}, trophy: {width: 164, height: 214, zIndex: 2}, coinLarge: {position: 'absolute', width: 112, height: 112, right: 16, top: 27, transform: [{rotate: '12deg'}]}, coinSmall: {position: 'absolute', width: 72, height: 72, left: 22, bottom: 56, transform: [{rotate: '-15deg'}]}, spark: {position: 'absolute', fontFamily: 'Baloo2-Bold', color: colors.yellow}, sparkOne: {fontSize: 45, left: 38, top: 34}, sparkTwo: {fontSize: 40, right: 40, bottom: 68, color: colors.pink}, badgeCard: {position: 'absolute', zIndex: 5, left: 10, top: 28, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 18, paddingVertical: 7, paddingHorizontal: 8, elevation: 7, transform: [{rotate: '-5deg'}]}, badgeImage: {width: 45, height: 45}, badgeTitle: {fontFamily: 'Baloo2-ExtraBold', color: colors.purple, fontSize: 12}, badgeSub: {fontFamily: 'Baloo2-Medium', color: '#81758D', fontSize: 9}, streakPill: {position: 'absolute', zIndex: 5, bottom: 22, backgroundColor: '#FFF', borderRadius: 20, paddingLeft: 16, paddingRight: 6, height: 48, flexDirection: 'row', alignItems: 'center', gap: 10, elevation: 6}, streakText: {fontFamily: 'Baloo2-ExtraBold', color: colors.ink, fontSize: 12}, streakFlame: {width: 36, height: 36, borderRadius: 13, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center'}, streakFlameText: {fontFamily: 'Baloo2-ExtraBold', color: '#FFF', fontSize: 16},
  welcome: {flex: 1, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', padding: 28}, welcomeCircle: {width: 280, height: 280, borderRadius: 140, backgroundColor: '#F0E2FF', alignItems: 'center', justifyContent: 'center'}, welcomeLogo: {width: 250, height: 130}, welcomeTitle: {fontFamily: 'Baloo2-ExtraBold', color: colors.ink, fontSize: 30, textAlign: 'center', marginTop: 32}, welcomeDescription: {fontFamily: 'Baloo2-Medium', color: '#6F637D', fontSize: 17, marginTop: 6}, startButton: {marginTop: 28, height: 56, minWidth: 210, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.purple}, startText: {fontFamily: 'Baloo2-Bold', color: '#FFF', fontSize: 18},
  webScreen: {flex: 1, backgroundColor: '#FFF'}, webView: {flex: 1}, webState: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center', padding: 28, backgroundColor: colors.cream}, webLogo: {width: 230, height: 100, marginBottom: 24}, webStateText: {fontFamily: 'Baloo2-Medium', color: '#6F637D', fontSize: 16, textAlign: 'center', marginTop: 14}, webErrorTitle: {fontFamily: 'Baloo2-Bold', color: colors.ink, fontSize: 22, textAlign: 'center'},
});
export default App;
